### ISSUE TITLE
load pretrained model from .pth

### ISSUE THREAD

**Issue by HaoRan-hash** [tensorlayer/TensorLayerX#18]
I write a model using Pytorch, and save its `state_dict()` to .pth. Now I want to use tensorlayerx to write it, so other people (using tensorflow etc.) can use this model.
My model definition is same in Pytorch and Tensorlayerx, but I can't load pretrained model of .pth in tensorlayerx.
Below is my code. (simple model is used here for clarity, the actual model is more complex than this)
```
"""
a_torch.py
"""
import torch
from torch import nn

class A(nn.Module):
    def __init__(self):
        super(A, self).__init__()
        self.conv = nn.Conv2d(3, 16, kernel_size=1)
        self.bn = nn.BatchNorm2d(16)
        self.relu = nn.ReLU(inplace=True)
    
    def forward(self, x):
        return self.act(self.bn(self.conv(x)))

if __name__ == '__main__':
    a = A()
    torch.save(a.state_dict(), 'a.pth')
```
```
"""
a_tlx.py
"""
import tensorlayerx as tlx
import torch
from tensorlayerx import nn

class A(nn.Module):
    def __init__(self):
        super(A, self).__init__()
        self.conv = nn.Conv2d(16, kernel_size=1, data_format='channels_first')
        self.bn = nn.BatchNorm2d(num_features=16, data_format='channels_first')
        self.relu = nn.activation.ReLU()
    
    def forward(self, x):
        return self.act(self.bn(self.conv(x)))

def pth2npz(pth_path):
    temp = torch.load(pth_path)   # type(temp) = OrderedDict
    tlx.files.save_npz_dict(temp.items(), pth_path.split('.')[0] + '.npz')

if __name__ == '__main__':
    a = A()
    pth2npz('a.pth')
    tlx.files.load_and_assign_npz_dict('a.npz', a)
```
First run `a_torch.py`, then run `a_tlx.py`.
The error is below.
```
Using PyTorch backend.
Traceback (most recent call last):
  File "test/test_03.py", line 25, in <module>
    tlx.files.load_and_assign_npz_dict('test/a.npz', a)
  File "/home/mchen/anaconda3/envs/kpconv/lib/python3.8/site-packages/tensorlayerx/files/utils.py", line 2208, in load_and_assign_npz_dict
    raise RuntimeError(
RuntimeError: Weights named 'conv.weight' not found in network. Hint: set argument skip=Ture if you want to skip redundant or mismatch weights
```
Then I debug and look at the `tlx.files.load_and_assign_npz_dict()` source code. I find tensorlayerx parameter name is different from PyTorch. This results in key mismatch when loading pre-trained model.
In the following two figures, the first is the parameter name of PyTorch and the second is the parameter name of TensorLayerx.
![屏幕截图 2022-08-07 202607](https://user-images.githubusercontent.com/54461374/183290533-6a71c50d-eff6-4024-81c9-c14201bab153.jpg)
![屏幕截图 2022-08-07 202555](https://user-images.githubusercontent.com/54461374/183290542-7d190eed-1123-478b-aba6-ea7e339b57ea.jpg)
Now the solution I can think of is to write a key map table, but it is hard for large model. So can you give me a simple solution ? (same model definition in pytorch and tensorlayerx, load pretrained model in .pth) :grin:

**Comment by Laicheng0830** [comment]
Thanks for your advice. You can find examples [here](https://github.com/tensorlayer/TensorLayerX/blob/main/examples/basic_tutorials/tutorial_load_pytorch_parameters_to_tensorlayerx.py.)

**Comment by HaoRan-hash** [comment]
Thank you.

**Comment by qzhiyue** [comment]
Issue Description

os.environ['TL_BACKEND'] = 'torch'
and using gpu0
When I try to put my model and variable into cuda:
```python 
net.cuda()
x, y, y_cls = Variable(x).cuda(), Variable(y).cuda(), Variable(y_cls).cuda()
```
an error occurred here:
```python 
class PSPUpsample(tlx.nn.Module):
    def __init__(self, in_channels, out_channels):
        super().__init__()
        self.conv = tlx.nn.Sequential(
            tlx.nn.Conv2d(in_channels=in_channels, out_channels=out_channels, kernel_size=3, padding=1, data_format='channels_first'),
            tlx.nn.BatchNorm2d(num_features=out_channels, data_format='channels_first'),
            tlx.layers.PRelu()
        )
    def forward(self, x):
        h, w = 2 * x.size(2), 2 * x.size(3)
        p = tlx.layers.UpSampling2d(scale=(h / x.size(2), w / x.size(3)), method='bilinear',
                                    data_format='channels_first')(x)
        return self.conv(p) 
```
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument weight in method wrapper__prelu)

When I put the 'p' into 'cuda:0' before 'return', like this:
```python 
p = p.to_device('cuda:0')
```
the error also occurred.
When I put the 'p' into cpu, it shows that the model in gpu and it doesn't work.

Thank you!
