### ISSUE TITLE
tlx.split的pytorch版本实现错误

### ISSUE THREAD

**Issue by zqwang-cn** [tensorlayer/TensorLayerX#24]
### New Issue Checklist

- [x] I have read the [Contribution Guidelines](https://github.com/tensorlayer/tensorlayer/blob/master/CONTRIBUTING.md)
- [x] I searched for [existing GitHub issues](https://github.com/tensorlayer/tensorlayer/issues)

### Issue Description

tlx.split的pytorch版本实现错误。tlx.split的第2个参数num_or_size_splits类型为int时，表示需要拆分成的tensor数量；但是在torch.split中第2个参数的意义为拆分出的每个tensor中在该维度上的长度。因此需要在调用前将该参数进行转换。

**Comment by hanjr92** [comment]
已修复 #26
