### ISSUE TITLE
希望添加一些常用功能

### ISSUE THREAD

**Issue by zqwang-cn** [tensorlayer/TensorLayerX#25]
### New Issue Checklist

- [x] I have read the [Contribution Guidelines](https://github.com/tensorlayer/tensorlayer/blob/master/CONTRIBUTING.md)
- [x] I searched for [existing GitHub issues](https://github.com/tensorlayer/tensorlayer/issues)

### Issue Description

希望添加一些常用功能的官方版本，否则每个用户需要自行实现。例如：

- NMS
- topk
- flatten
- numel
- identity
- mish, swish, hardsigmoid等激活函数

**Comment by hanjr92** [comment]
topk, flatten,identity 可以通过 tlx.ops使用
mish, swish, hardsigmoid可以通过 tlx.nn 使用
我会尽快添加 numel和nms对应功能

**Comment by qiutzh** [comment]
hardswish激活函数也不存在

**Comment by hanjr92** [comment]
hardswish  nms  iou等功能已经添加
