### ISSUE TITLE
LayerNorm layer parameter initialization

### ISSUE THREAD

**Issue by qiutzh** [tensorlayer/TensorLayerX#30]
### New Issue Checklist

- [x] I have read the [Contribution Guidelines](https://github.com/tensorlayer/tensorlayer/blob/master/CONTRIBUTING.md)
- [x] I searched for [existing GitHub issues](https://github.com/tensorlayer/tensorlayer/issues)

### Issue Description

请问，tlx中LayerNorm层参数初始化方式是怎样的，发现执行 tlx.nn.LayerNorm(num) 语句后，虽然给gamma_init、beta_init赋了默认值，但参数维度向量的数值并不能拿到，可训练的权重向量为空。

tlx version：0.5.6

### Reproducible Code

```python
a = tlx.nn.LayerNorm(128)

# compare
b = paddle.nn.LayerNorm(128)
```

**Comment by qiutzh** [comment]
I know

**Comment by hanjr92** [comment]
之前的layernorm是在拿到 实际的input 之后才会开始进行初始化，也就是在第一次执行计算的时候创建参数。我更新了一下代码，现在可以在初始化layernorm的时候也同时创建参数，和paddle、torch保持一致。

**Comment by qiutzh** [comment]
@是0.5.6版本也可以了吗？

**Comment by hanjr92** [comment]
没有更新到分支上，更新到master主分支了，你使用 pip install git+https://github.com/tensorlayer/tensorlayerx.git  来更新一下 tensorlayerx吧

**Comment by qiutzh** [comment]
好的
