### ISSUE TITLE
tlx.nn.Swish()与paddle.nn.Swish()的结果有细微差别

### ISSUE THREAD

**Issue by moshizhiyin** [tensorlayer/TensorLayerX#35]
### tlx：
[-0.16246916,  1.40204561,  0.85213524, ...,  0.85800600,
            1.10605156,  1.11549926],
          [-0.04873780,  0.28885114,  0.15792340, ...,  0.12375022,
            0.22599602,  0.53073120],
          [-0.09840852,  0.40172467,  0.15602632, ...,  0.09853011,
            0.29177830,  0.52241892]
### paddle:
[-0.16246916,  1.40204573,  0.85213524, ...,  0.85800600,
            1.10605145,  1.11549926],
          [-0.04873780,  0.28885114,  0.15792342, ...,  0.12375022,
            0.22599602,  0.53073120],
          [-0.09840852,  0.40172467,  0.15602632, ...,  0.09853011,
            0.29177833,  0.52241892]

**Comment by hanjr92** [comment]
已修复 #39
