### ISSUE TITLE
tensorlayerx.nn.PRelu()初始化时没有进行build，self.build()中inputs_shape没有进行说明

### ISSUE THREAD

**Issue by Eric-yuye** [tensorlayer/TensorLayerX#37]
class PRelu(Module):
    r"""Applies the element-wise function:

    .. math::
        \text{PReLU}(x) = \max(0,x) + a * \min(0,x)

    Parameters
    ----------
    num_parameters : int
        number of `a` to learn.  1, or the number of channels at input. Default: 1
    init : float
        the initial value of `a`. Default: 0.25
    data_format : str
        Data format that specifies the layout of input. It may be 'channels_last' or 'channels_first'. Default is 'channels_last'.
    name : None or str
        A unique layer name.

    Examples
    -----------
    >>> inputs = tlx.nn.Input([10, 5, 10])
    >>> prelulayer = tlx.nn.PRelu(num_parameters=5, init=0.25, data_format='channels_first')(inputs)

    References
    -----------
    - `Delving Deep into Rectifiers: Surpassing Human-Level Performance on ImageNet Classification <http://arxiv.org/abs/1502.01852>`__
    - `Convolutional Deep Belief Networks on CIFAR-10 [A. Krizhevsky, 2010] <http://www.cs.utoronto.ca/~kriz/conv-cifar10-aug2010.pdf>`__

    """

    def __init__(
        self, num_parameters = 1, init=0.25,  data_format='channels_last', name=None,
    ):

        super(PRelu, self).__init__(name)
        self.num_parameters = num_parameters
        self.init = init
        self.data_format = data_format

        logging.info("PRelu %s: num_parameters: %s" % (self.name, self.num_parameters))

    def __repr__(self):
        s = ('{classname}(')
        s += 'num_parameters={num_parameters},'
        s += 'init={init},'
        s += 'name={name}'
        s += ')'
        return s.format(classname=self.__class__.__name__, **self.__dict__)

    def build(self, inputs_shape):
        dim = len(inputs_shape)
        if self.data_format == 'channels_last':
            w_shape = (self.num_parameters, )
        elif self.data_format == 'channels_first':
            if dim == 4:
                w_shape = (1, self.num_parameters, 1, 1)
            elif dim == 3:
                w_shape = (1, self.num_parameters, 1)
            elif dim == 5:
                w_shape = (1, self.num_parameters, 1, 1, 1)
            elif dim < 3:
                w_shape = (self.num_parameters, )

        self.alpha = self._get_weights("alpha", shape=w_shape, init=tlx.initializers.constant(value=self.init))
        self.prelu = tlx.ops.PReLU(data_format = self.data_format)

    def forward(self, inputs):
        if self._forward_state == False:
            if self._built == False:
                self.build(tlx.get_tensor_shape(inputs))
                self._built = True
            self._forward_state = True

        output = self.prelu(inputs, self.alpha)

        if not self._nodes_fixed and self._build_graph:
            self._add_node(inputs, output)
            self._nodes_fixed = True
        return output

**Comment by hanjr92** [comment]
已修复 #39
